name: Build Docker
on: [push, workflow_dispatch]

env:
  IMAGE_NAME: udpspeeder
  TAG_LATEST: latest
  TAG_DEV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Date Tag
      run: echo "TAG_CURRENT=v$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{env.IMAGE_NAME}}:${{env.TAG_CURRENT}}
          ghcr.io/${{ github.repository_owner }}/${{env.IMAGE_NAME}}:${{env.TAG_LATEST}}
          ghcr.io/${{ github.repository_owner }}/${{env.IMAGE_NAME}}:${{env.TAG_DEV}}
